package e2country

var (
	CountryCodes = []*CountryCode{
		{Country: "Canada", CountryCode: "1", ISOCode2: "CA", ISOCode3: "CAN"},
		{Country: "United States", CountryCode: "1", ISOCode2: "US", ISOCode3: "USA"},
		{Country: "Kazakhstan", CountryCode: "7", ISOCode2: "KZ", ISOCode3: "KAZ"},
		{Country: "Russia", CountryCode: "7", ISOCode2: "RU", ISOCode3: "RUS"},
		{Country: "Egypt", CountryCode: "20", ISOCode2: "EG", ISOCode3: "EGY"},
		{Country: "South Africa", CountryCode: "27", ISOCode2: "ZA", ISOCode3: "ZAF"},
		{Country: "Greece", CountryCode: "30", ISOCode2: "GR", ISOCode3: "GRC"},
		{Country: "Netherlands", CountryCode: "31", ISOCode2: "NL", ISOCode3: "NLD"},
		{Country: "Belgium", CountryCode: "32", ISOCode2: "BE", ISOCode3: "BEL"},
		{Country: "France", CountryCode: "33", ISOCode2: "FR", ISOCode3: "FRA"},
		{Country: "Spain", CountryCode: "34", ISOCode2: "ES", ISOCode3: "ESP"},
		{Country: "Hungary", CountryCode: "36", ISOCode2: "HU", ISOCode3: "HUN"},
		{Country: "Italy", CountryCode: "39", ISOCode2: "IT", ISOCode3: "ITA"},
		{Country: "Romania", CountryCode: "40", ISOCode2: "RO", ISOCode3: "ROU"},
		{Country: "Switzerland", CountryCode: "41", ISOCode2: "CH", ISOCode3: "CHE"},
		{Country: "Austria", CountryCode: "43", ISOCode2: "AT", ISOCode3: "AUT"},
		{Country: "United Kingdom", CountryCode: "44", ISOCode2: "GB", ISOCode3: "GBR"},
		{Country: "Denmark", CountryCode: "45", ISOCode2: "DK", ISOCode3: "DNK"},
		{Country: "Sweden", CountryCode: "46", ISOCode2: "SE", ISOCode3: "SWE"},
		{Country: "Norway", CountryCode: "47", ISOCode2: "NO", ISOCode3: "NOR"},
		{Country: "Svalbard and Jan Mayen", CountryCode: "47", ISOCode2: "SJ", ISOCode3: "SJM"},
		{Country: "Poland", CountryCode: "48", ISOCode2: "PL", ISOCode3: "POL"},
		{Country: "Germany", CountryCode: "49", ISOCode2: "DE", ISOCode3: "DEU"},
		{Country: "Peru", CountryCode: "51", ISOCode2: "PE", ISOCode3: "PER"},
		{Country: "Mexico", CountryCode: "52", ISOCode2: "MX", ISOCode3: "MEX"},
		{Country: "Cuba", CountryCode: "53", ISOCode2: "CU", ISOCode3: "CUB"},
		{Country: "Argentina", CountryCode: "54", ISOCode2: "AR", ISOCode3: "ARG"},
		{Country: "Brazil", CountryCode: "55", ISOCode2: "BR", ISOCode3: "BRA"},
		{Country: "Chile", CountryCode: "56", ISOCode2: "CL", ISOCode3: "CHL"},
		{Country: "Colombia", CountryCode: "57", ISOCode2: "CO", ISOCode3: "COL"},
		{Country: "Venezuela", CountryCode: "58", ISOCode2: "VE", ISOCode3: "VEN"},
		{Country: "Malaysia", CountryCode: "60", ISOCode2: "MY", ISOCode3: "MYS"},
		{Country: "Australia", CountryCode: "61", ISOCode2: "AU", ISOCode3: "AUS"},
		{Country: "Christmas Island", CountryCode: "61", ISOCode2: "CX", ISOCode3: "CXR"},
		{Country: "Cocos Islands", CountryCode: "61", ISOCode2: "CC", ISOCode3: "CCK"},
		{Country: "Indonesia", CountryCode: "62", ISOCode2: "Key", ISOCode3: "IDN"},
		{Country: "Philippines", CountryCode: "63", ISOCode2: "PH", ISOCode3: "PHL"},
		{Country: "New Zealand", CountryCode: "64", ISOCode2: "NZ", ISOCode3: "NZL"},
		{Country: "Pitcairn", CountryCode: "64", ISOCode2: "PN", ISOCode3: "PCN"},
		{Country: "Singapore", CountryCode: "65", ISOCode2: "SG", ISOCode3: "SGP"},
		{Country: "Thailand", CountryCode: "66", ISOCode2: "TH", ISOCode3: "THA"},
		{Country: "Japan", CountryCode: "81", ISOCode2: "JP", ISOCode3: "JPN"},
		{Country: "South Korea", CountryCode: "82", ISOCode2: "KR", ISOCode3: "KOR"},
		{Country: "Vietnam", CountryCode: "84", ISOCode2: "VN", ISOCode3: "VNM"},
		{Country: "China", CountryCode: "86", ISOCode2: "CN", ISOCode3: "CHN"},
		{Country: "Turkey", CountryCode: "90", ISOCode2: "TR", ISOCode3: "TUR"},
		{Country: "India", CountryCode: "91", ISOCode2: "IN", ISOCode3: "IND"},
		{Country: "Pakistan", CountryCode: "92", ISOCode2: "PK", ISOCode3: "PAK"},
		{Country: "Afghanistan", CountryCode: "93", ISOCode2: "AF", ISOCode3: "AFG"},
		{Country: "Sri Lanka", CountryCode: "94", ISOCode2: "LK", ISOCode3: "LKA"},
		{Country: "Myanmar", CountryCode: "95", ISOCode2: "MM", ISOCode3: "MMR"},
		{Country: "Iran", CountryCode: "98", ISOCode2: "IR", ISOCode3: "IRN"},
		{Country: "South Sudan", CountryCode: "211", ISOCode2: "SS", ISOCode3: "SSD"},
		{Country: "Morocco", CountryCode: "212", ISOCode2: "MA", ISOCode3: "MAR"},
		{Country: "Western Sahara", CountryCode: "212", ISOCode2: "EH", ISOCode3: "ESH"},
		{Country: "Algeria", CountryCode: "213", ISOCode2: "DZ", ISOCode3: "DZA"},
		{Country: "Tunisia", CountryCode: "216", ISOCode2: "TN", ISOCode3: "TUN"},
		{Country: "Libya", CountryCode: "218", ISOCode2: "LY", ISOCode3: "LBY"},
		{Country: "Gambia", CountryCode: "220", ISOCode2: "GM", ISOCode3: "GMB"},
		{Country: "Senegal", CountryCode: "221", ISOCode2: "SN", ISOCode3: "SEN"},
		{Country: "Mauritania", CountryCode: "222", ISOCode2: "MR", ISOCode3: "MRT"},
		{Country: "Mali", CountryCode: "223", ISOCode2: "ML", ISOCode3: "MLI"},
		{Country: "Guinea", CountryCode: "224", ISOCode2: "GN", ISOCode3: "GIN"},
		{Country: "Ivory Coast", CountryCode: "225", ISOCode2: "CI", ISOCode3: "CIV"},
		{Country: "Burkina Faso", CountryCode: "226", ISOCode2: "BF", ISOCode3: "BFA"},
		{Country: "Niger", CountryCode: "227", ISOCode2: "NE", ISOCode3: "NER"},
		{Country: "Togo", CountryCode: "228", ISOCode2: "TG", ISOCode3: "TGO"},
		{Country: "Benin", CountryCode: "229", ISOCode2: "BJ", ISOCode3: "BEN"},
		{Country: "Mauritius", CountryCode: "230", ISOCode2: "MU", ISOCode3: "MUS"},
		{Country: "Liberia", CountryCode: "231", ISOCode2: "LR", ISOCode3: "LBR"},
		{Country: "Sierra Leone", CountryCode: "232", ISOCode2: "SL", ISOCode3: "SLE"},
		{Country: "Ghana", CountryCode: "233", ISOCode2: "GH", ISOCode3: "GHA"},
		{Country: "Nigeria", CountryCode: "234", ISOCode2: "NG", ISOCode3: "NGA"},
		{Country: "Chad", CountryCode: "235", ISOCode2: "TD", ISOCode3: "TCD"},
		{Country: "Central African Republic", CountryCode: "236", ISOCode2: "CF", ISOCode3: "CAF"},
		{Country: "Cameroon", CountryCode: "237", ISOCode2: "CM", ISOCode3: "CMR"},
		{Country: "Cape Verde", CountryCode: "238", ISOCode2: "CV", ISOCode3: "CPV"},
		{Country: "Sao Tome and Principe", CountryCode: "239", ISOCode2: "ST", ISOCode3: "STP"},
		{Country: "Equatorial Guinea", CountryCode: "240", ISOCode2: "GQ", ISOCode3: "GNQ"},
		{Country: "Gabon", CountryCode: "241", ISOCode2: "GA", ISOCode3: "GAB"},
		{Country: "Republic of the Congo", CountryCode: "242", ISOCode2: "CG", ISOCode3: "COG"},
		{Country: "Democratic Republic of the Congo", CountryCode: "243", ISOCode2: "CD", ISOCode3: "COD"},
		{Country: "Angola", CountryCode: "244", ISOCode2: "AO", ISOCode3: "AGO"},
		{Country: "Guinea-Bissau", CountryCode: "245", ISOCode2: "GW", ISOCode3: "GNB"},
		{Country: "British Indian Ocean Territory", CountryCode: "246", ISOCode2: "IO", ISOCode3: "IOT"},
		{Country: "Seychelles", CountryCode: "248", ISOCode2: "SC", ISOCode3: "SYC"},
		{Country: "Sudan", CountryCode: "249", ISOCode2: "SD", ISOCode3: "SDN"},
		{Country: "Rwanda", CountryCode: "250", ISOCode2: "RW", ISOCode3: "RWA"},
		{Country: "Ethiopia", CountryCode: "251", ISOCode2: "ET", ISOCode3: "ETH"},
		{Country: "Somalia", CountryCode: "252", ISOCode2: "SO", ISOCode3: "SOM"},
		{Country: "Djibouti", CountryCode: "253", ISOCode2: "DJ", ISOCode3: "DJI"},
		{Country: "Kenya", CountryCode: "254", ISOCode2: "KE", ISOCode3: "KEN"},
		{Country: "Tanzania", CountryCode: "255", ISOCode2: "TZ", ISOCode3: "TZA"},
		{Country: "Uganda", CountryCode: "256", ISOCode2: "UG", ISOCode3: "UGA"},
		{Country: "Burundi", CountryCode: "257", ISOCode2: "BI", ISOCode3: "BDI"},
		{Country: "Mozambique", CountryCode: "258", ISOCode2: "MZ", ISOCode3: "MOZ"},
		{Country: "Zambia", CountryCode: "260", ISOCode2: "ZM", ISOCode3: "ZMB"},
		{Country: "Madagascar", CountryCode: "261", ISOCode2: "MG", ISOCode3: "MDG"},
		{Country: "Mayotte", CountryCode: "262", ISOCode2: "YT", ISOCode3: "MYT"},
		{Country: "Reunion", CountryCode: "262", ISOCode2: "RE", ISOCode3: "REU"},
		{Country: "Zimbabwe", CountryCode: "263", ISOCode2: "ZW", ISOCode3: "ZWE"},
		{Country: "Namibia", CountryCode: "264", ISOCode2: "NA", ISOCode3: "NAM"},
		{Country: "Malawi", CountryCode: "265", ISOCode2: "MW", ISOCode3: "MWI"},
		{Country: "Lesotho", CountryCode: "266", ISOCode2: "LS", ISOCode3: "LSO"},
		{Country: "Botswana", CountryCode: "267", ISOCode2: "BW", ISOCode3: "BWA"},
		{Country: "Swaziland", CountryCode: "268", ISOCode2: "SZ", ISOCode3: "SWZ"},
		{Country: "Comoros", CountryCode: "269", ISOCode2: "KM", ISOCode3: "COM"},
		{Country: "Saint Helena", CountryCode: "290", ISOCode2: "SH", ISOCode3: "SHN"},
		{Country: "Eritrea", CountryCode: "291", ISOCode2: "ER", ISOCode3: "ERI"},
		{Country: "Aruba", CountryCode: "297", ISOCode2: "AW", ISOCode3: "ABW"},
		{Country: "Faroe Islands", CountryCode: "298", ISOCode2: "FO", ISOCode3: "FRO"},
		{Country: "Greenland", CountryCode: "299", ISOCode2: "GL", ISOCode3: "GRL"},
		{Country: "Gibraltar", CountryCode: "350", ISOCode2: "GI", ISOCode3: "GIB"},
		{Country: "Portugal", CountryCode: "351", ISOCode2: "PT", ISOCode3: "PRT"},
		{Country: "Luxembourg", CountryCode: "352", ISOCode2: "LU", ISOCode3: "LUX"},
		{Country: "Ireland", CountryCode: "353", ISOCode2: "IE", ISOCode3: "IRL"},
		{Country: "Iceland", CountryCode: "354", ISOCode2: "IS", ISOCode3: "ISL"},
		{Country: "Albania", CountryCode: "355", ISOCode2: "AL", ISOCode3: "ALB"},
		{Country: "Malta", CountryCode: "356", ISOCode2: "MT", ISOCode3: "MLT"},
		{Country: "Cyprus", CountryCode: "357", ISOCode2: "CY", ISOCode3: "CYP"},
		{Country: "Finland", CountryCode: "358", ISOCode2: "FI", ISOCode3: "FIN"},
		{Country: "Bulgaria", CountryCode: "359", ISOCode2: "BG", ISOCode3: "BGR"},
		{Country: "Lithuania", CountryCode: "370", ISOCode2: "LT", ISOCode3: "LTU"},
		{Country: "Latvia", CountryCode: "371", ISOCode2: "LV", ISOCode3: "LVA"},
		{Country: "Estonia", CountryCode: "372", ISOCode2: "EE", ISOCode3: "EST"},
		{Country: "Moldova", CountryCode: "373", ISOCode2: "MD", ISOCode3: "MDA"},
		{Country: "Armenia", CountryCode: "374", ISOCode2: "AM", ISOCode3: "ARM"},
		{Country: "Belarus", CountryCode: "375", ISOCode2: "BY", ISOCode3: "BLR"},
		{Country: "Andorra", CountryCode: "376", ISOCode2: "AD", ISOCode3: "AND"},
		{Country: "Monaco", CountryCode: "377", ISOCode2: "MC", ISOCode3: "MCO"},
		{Country: "San Marino", CountryCode: "378", ISOCode2: "SM", ISOCode3: "SMR"},
		{Country: "Vatican", CountryCode: "379", ISOCode2: "VA", ISOCode3: "VAT"},
		{Country: "Ukraine", CountryCode: "380", ISOCode2: "UA", ISOCode3: "UKR"},
		{Country: "Serbia", CountryCode: "381", ISOCode2: "RS", ISOCode3: "SRB"},
		{Country: "Montenegro", CountryCode: "382", ISOCode2: "ME", ISOCode3: "MNE"},
		{Country: "Kosovo", CountryCode: "383", ISOCode2: "XK", ISOCode3: "XKX"},
		{Country: "Croatia", CountryCode: "385", ISOCode2: "HR", ISOCode3: "HRV"},
		{Country: "Slovenia", CountryCode: "386", ISOCode2: "SI", ISOCode3: "SVN"},
		{Country: "Bosnia and Herzegovina", CountryCode: "387", ISOCode2: "BA", ISOCode3: "BIH"},
		{Country: "Macedonia", CountryCode: "389", ISOCode2: "MK", ISOCode3: "MKD"},
		{Country: "Czech Republic", CountryCode: "420", ISOCode2: "CZ", ISOCode3: "CZE"},
		{Country: "Slovakia", CountryCode: "421", ISOCode2: "SK", ISOCode3: "SVK"},
		{Country: "Liechtenstein", CountryCode: "423", ISOCode2: "LI", ISOCode3: "LIE"},
		{Country: "Falkland Islands", CountryCode: "500", ISOCode2: "FK", ISOCode3: "FLK"},
		{Country: "Belize", CountryCode: "501", ISOCode2: "BZ", ISOCode3: "BLZ"},
		{Country: "Guatemala", CountryCode: "502", ISOCode2: "GT", ISOCode3: "GTM"},
		{Country: "El Salvador", CountryCode: "503", ISOCode2: "SV", ISOCode3: "SLV"},
		{Country: "Honduras", CountryCode: "504", ISOCode2: "HN", ISOCode3: "HND"},
		{Country: "Nicaragua", CountryCode: "505", ISOCode2: "NI", ISOCode3: "NIC"},
		{Country: "Costa Rica", CountryCode: "506", ISOCode2: "CR", ISOCode3: "CRI"},
		{Country: "Panama", CountryCode: "507", ISOCode2: "PA", ISOCode3: "PAN"},
		{Country: "Saint Pierre and Miquelon", CountryCode: "508", ISOCode2: "PM", ISOCode3: "SPM"},
		{Country: "Haiti", CountryCode: "509", ISOCode2: "HT", ISOCode3: "HTI"},
		{Country: "Saint Barthelemy", CountryCode: "590", ISOCode2: "BL", ISOCode3: "BLM"},
		{Country: "Saint Martin", CountryCode: "590", ISOCode2: "MF", ISOCode3: "MAF"},
		{Country: "Bolivia", CountryCode: "591", ISOCode2: "BO", ISOCode3: "BOL"},
		{Country: "Guyana", CountryCode: "592", ISOCode2: "GY", ISOCode3: "GUY"},
		{Country: "Ecuador", CountryCode: "593", ISOCode2: "EC", ISOCode3: "ECU"},
		{Country: "Paraguay", CountryCode: "595", ISOCode2: "PY", ISOCode3: "PRY"},
		{Country: "Suriname", CountryCode: "597", ISOCode2: "SR", ISOCode3: "SUR"},
		{Country: "Uruguay", CountryCode: "598", ISOCode2: "UY", ISOCode3: "URY"},
		{Country: "Curacao", CountryCode: "599", ISOCode2: "CW", ISOCode3: "CUW"},
		{Country: "Netherlands Antilles", CountryCode: "599", ISOCode2: "AN", ISOCode3: "ANT"},
		{Country: "East Timor", CountryCode: "670", ISOCode2: "TL", ISOCode3: "TLS"},
		{Country: "Antarctica", CountryCode: "672", ISOCode2: "AQ", ISOCode3: "ATA"},
		{Country: "Brunei", CountryCode: "673", ISOCode2: "BN", ISOCode3: "BRN"},
		{Country: "Nauru", CountryCode: "674", ISOCode2: "NR", ISOCode3: "NRU"},
		{Country: "Papua New Guinea", CountryCode: "675", ISOCode2: "PG", ISOCode3: "PNG"},
		{Country: "Tonga", CountryCode: "676", ISOCode2: "TO", ISOCode3: "TON"},
		{Country: "Solomon Islands", CountryCode: "677", ISOCode2: "SB", ISOCode3: "SLB"},
		{Country: "Vanuatu", CountryCode: "678", ISOCode2: "VU", ISOCode3: "VUT"},
		{Country: "Fiji", CountryCode: "679", ISOCode2: "FJ", ISOCode3: "FJI"},
		{Country: "Palau", CountryCode: "680", ISOCode2: "PW", ISOCode3: "PLW"},
		{Country: "Wallis and Futuna", CountryCode: "681", ISOCode2: "WF", ISOCode3: "WLF"},
		{Country: "Cook Islands", CountryCode: "682", ISOCode2: "CK", ISOCode3: "COK"},
		{Country: "Niue", CountryCode: "683", ISOCode2: "NU", ISOCode3: "NIU"},
		{Country: "Samoa", CountryCode: "685", ISOCode2: "WS", ISOCode3: "WSM"},
		{Country: "Kiribati", CountryCode: "686", ISOCode2: "KI", ISOCode3: "KIR"},
		{Country: "New Caledonia", CountryCode: "687", ISOCode2: "NC", ISOCode3: "NCL"},
		{Country: "Tuvalu", CountryCode: "688", ISOCode2: "TV", ISOCode3: "TUV"},
		{Country: "French Polynesia", CountryCode: "689", ISOCode2: "PF", ISOCode3: "PYF"},
		{Country: "Tokelau", CountryCode: "690", ISOCode2: "TK", ISOCode3: "TKL"},
		{Country: "Micronesia", CountryCode: "691", ISOCode2: "FM", ISOCode3: "FSM"},
		{Country: "Marshall Islands", CountryCode: "692", ISOCode2: "MH", ISOCode3: "MHL"},
		{Country: "North Korea", CountryCode: "850", ISOCode2: "KP", ISOCode3: "PRK"},
		{Country: "Hong Kong", CountryCode: "852", ISOCode2: "HK", ISOCode3: "HKG"},
		{Country: "Macau", CountryCode: "853", ISOCode2: "MO", ISOCode3: "MAC"},
		{Country: "Cambodia", CountryCode: "855", ISOCode2: "KH", ISOCode3: "KHM"},
		{Country: "Laos", CountryCode: "856", ISOCode2: "LA", ISOCode3: "LAO"},
		{Country: "Bangladesh", CountryCode: "880", ISOCode2: "BD", ISOCode3: "BGD"},
		{Country: "Taiwan", CountryCode: "886", ISOCode2: "TW", ISOCode3: "TWN"},
		{Country: "Maldives", CountryCode: "960", ISOCode2: "MV", ISOCode3: "MDV"},
		{Country: "Lebanon", CountryCode: "961", ISOCode2: "LB", ISOCode3: "LBN"},
		{Country: "Jordan", CountryCode: "962", ISOCode2: "JO", ISOCode3: "JOR"},
		{Country: "Syria", CountryCode: "963", ISOCode2: "SY", ISOCode3: "SYR"},
		{Country: "Iraq", CountryCode: "964", ISOCode2: "IQ", ISOCode3: "IRQ"},
		{Country: "Kuwait", CountryCode: "965", ISOCode2: "KW", ISOCode3: "KWT"},
		{Country: "Saudi Arabia", CountryCode: "966", ISOCode2: "SA", ISOCode3: "SAU"},
		{Country: "Yemen", CountryCode: "967", ISOCode2: "YE", ISOCode3: "YEM"},
		{Country: "Oman", CountryCode: "968", ISOCode2: "OM", ISOCode3: "OMN"},
		{Country: "Palestine", CountryCode: "970", ISOCode2: "PS", ISOCode3: "PSE"},
		{Country: "United Arab Emirates", CountryCode: "971", ISOCode2: "AE", ISOCode3: "ARE"},
		{Country: "Israel", CountryCode: "972", ISOCode2: "IL", ISOCode3: "ISR"},
		{Country: "Bahrain", CountryCode: "973", ISOCode2: "BH", ISOCode3: "BHR"},
		{Country: "Qatar", CountryCode: "974", ISOCode2: "QA", ISOCode3: "QAT"},
		{Country: "Bhutan", CountryCode: "975", ISOCode2: "BT", ISOCode3: "BTN"},
		{Country: "Mongolia", CountryCode: "976", ISOCode2: "MN", ISOCode3: "MNG"},
		{Country: "Nepal", CountryCode: "977", ISOCode2: "NP", ISOCode3: "NPL"},
		{Country: "Tajikistan", CountryCode: "992", ISOCode2: "TJ", ISOCode3: "TJK"},
		{Country: "Turkmenistan", CountryCode: "993", ISOCode2: "TM", ISOCode3: "TKM"},
		{Country: "Azerbaijan", CountryCode: "994", ISOCode2: "AZ", ISOCode3: "AZE"},
		{Country: "Georgia", CountryCode: "995", ISOCode2: "GE", ISOCode3: "GEO"},
		{Country: "Kyrgyzstan", CountryCode: "996", ISOCode2: "KG", ISOCode3: "KGZ"},
		{Country: "Uzbekistan", CountryCode: "998", ISOCode2: "UZ", ISOCode3: "UZB"},
		{Country: "Bahamas", CountryCode: "1-242", ISOCode2: "BS", ISOCode3: "BHS"},
		{Country: "Barbados", CountryCode: "1-246", ISOCode2: "BB", ISOCode3: "BRB"},
		{Country: "Anguilla", CountryCode: "1-264", ISOCode2: "AI", ISOCode3: "AIA"},
		{Country: "Antigua and Barbuda", CountryCode: "1-268", ISOCode2: "AG", ISOCode3: "ATG"},
		{Country: "British Virgin Islands", CountryCode: "1-284", ISOCode2: "VG", ISOCode3: "VGB"},
		{Country: "U.S. Virgin Islands", CountryCode: "1-340", ISOCode2: "VI", ISOCode3: "VIR"},
		{Country: "Cayman Islands", CountryCode: "1-345", ISOCode2: "KY", ISOCode3: "CYM"},
		{Country: "Bermuda", CountryCode: "1-441", ISOCode2: "BM", ISOCode3: "BMU"},
		{Country: "Grenada", CountryCode: "1-473", ISOCode2: "GD", ISOCode3: "GRD"},
		{Country: "Turks and Caicos Islands", CountryCode: "1-649", ISOCode2: "TC", ISOCode3: "TCA"},
		{Country: "Montserrat", CountryCode: "1-664", ISOCode2: "MS", ISOCode3: "MSR"},
		{Country: "Northern Mariana Islands", CountryCode: "1-670", ISOCode2: "MP", ISOCode3: "MNP"},
		{Country: "Guam", CountryCode: "1-671", ISOCode2: "GU", ISOCode3: "GUM"},
		{Country: "American Samoa", CountryCode: "1-684", ISOCode2: "AS", ISOCode3: "ASM"},
		{Country: "Sint Maarten", CountryCode: "1-721", ISOCode2: "SX", ISOCode3: "SXM"},
		{Country: "Saint Lucia", CountryCode: "1-758", ISOCode2: "LC", ISOCode3: "LCA"},
		{Country: "Dominica", CountryCode: "1-767", ISOCode2: "DM", ISOCode3: "DMA"},
		{Country: "Saint Vincent and the Grenadines", CountryCode: "1-784", ISOCode2: "VC", ISOCode3: "VCT"},
		{Country: "Puerto Rico", CountryCode: "1-787", ISOCode2: " 1-939", ISOCode3: "PR"},
		{Country: "Dominican Republic", CountryCode: "1-809", ISOCode2: " 1-829", ISOCode3: " 1-849"},
		{Country: "Trinidad and Tobago", CountryCode: "1-868", ISOCode2: "TT", ISOCode3: "TTO"},
		{Country: "Saint Kitts and Nevis", CountryCode: "1-869", ISOCode2: "KN", ISOCode3: "KNA"},
		{Country: "Jamaica", CountryCode: "1-876", ISOCode2: "JM", ISOCode3: "JAM"},
		{Country: "Guernsey", CountryCode: "44-1481", ISOCode2: "GG", ISOCode3: "GGY"},
		{Country: "Jersey", CountryCode: "44-1534", ISOCode2: "JE", ISOCode3: "JEY"},
		{Country: "Isle of Man", CountryCode: "44-1624", ISOCode2: "IM", ISOCode3: "IMN"},
	}
)

type CountryCode struct {
	Country     string
	CountryCode string
	ISOCode2    string
	ISOCode3    string
}
